project:
  type: book

book:
  title: "MATH337: Changepoint Detection"
  author: "Gaetano Romano"
  date: "11/01/24"
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 1_intro_cusum.qmd
    - 2_control.qmd
    - 3_multiple_changes.qmd
    - 4_algos_and_penalties.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

